### PR TITLE
update to latest version

### PR DESCRIPTION
**Pull request by xyfy**
update abp to 5.0 RC1

update .net  to Net 6.0

### CODE REVIEW

**Comment by maihungdev** [comment]
Good job <3

**Comment by gterdem** [comment]
Thank you for your PR, we'll check it as soon as possible.

**Comment by 52dzd** [comment]
@enisn  why you donot take this pr?

**Comment by enisn** [comment]
There were some ongoing development processes, so that made some conflicts, can you resolve @xyfy ?

**Comment by enisn** [comment]
Conflicts are now resolved

**Comment by 52dzd** [comment]
> Conflicts are now resolved

so you can merge this pr now?

**Comment by enisn** [comment]
Looks good 👍

**Pull request merged**
