### PR TITLE
Payment Service with PayPal

### PR DESCRIPTION
**Pull request by enisn**
Closes https://github.com/abpframework/abp/issues/10296

### CODE REVIEW

**Comment by maihungdev** [comment]
Can you continue to develop this feature?
I want to see how services are related to each other.
Is it phase 2?

**Comment by gterdem** [comment]
@maihungdev Hello, we have decided to make some structural changes to simplify the solution such as removing multi-tenancy and removing internal gateway (after started using static proxies).
We plan to prepare the base solution can be up and running at both localhost and k8s cluster.
Afterwards, we will continue on business related logic.
Thank you for your interest.

**Comment by enisn** [comment]
It's no longer draft, I've fixed broken tests

**Comment by enisn** [comment]
Conflicts have been resolved

**Pull request merged**
