### PR TITLE
Fix Swagger Clients-Scopes Keycloak

### PR DESCRIPTION
**Pull request by alihdev**
issue : Keycloak "We are sorry... Invalid parameter: redirect_uri" with WebGateway_Swagger client 
solved by:
- add new client for WebGateway_Swagger
- add scopes to SwaggerClient-WebGateway_Swagger

### CODE REVIEW

**Comment by alihdev** [comment]
https://github.com/abpframework/abp/issues/15183#issuecomment-1361715408

**Comment by gterdem** [comment]
We've already published new version for [Volo.Abp.Swashbuckle](https://www.nuget.org/packages/Volo.Abp.Swashbuckle). 
You can simply update the version in https://github.com/abpframework/eShopOnAbp/blob/127e993e88196d3299e2fdf95a15e822889a954e/shared/EShopOnAbp.Shared.Hosting.AspNetCore/EShopOnAbp.Shared.Hosting.AspNetCore.csproj#L12

We are planning to update the whole project version to v7 after the final release is completed.

**Comment by alihdev** [comment]
We are looking forward to the new version, all the best .
But this commit https://github.com/abpframework/eShopOnAbp/pull/147#issue-1506743011 is about add new client **WebGateway_Swagger** and assign scopes.

**Comment by sevenNightL** [comment]
Excuse me, how is the problem being handled?

**Comment by alihdev** [comment]
> Excuse me, how is the problem being handled?

check : [commented](https://github.com/abpframework/eShopOnAbp/pull/147#issue-1506743011) & [changes](https://github.com/abpframework/eShopOnAbp/pull/147/files) @sevenNightL

**Comment by alihdev** [comment]
I closed it and created a new [PR-215](https://github.com/abpframework/eShopOnAbp/pull/215)

**Pull request closed without merging**
